runtime: python311 # Specify the Python version

entrypoint: streamlit run app.py --server.port $PORT --server.enableCORS false --server.enableXsrfProtection false

env_variables:
  GROQ_API_KEY: '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'

automatic_scaling:
  min_idle_instances: 1 # Minimum number of idle instances
  max_idle_instances: 2 # Maximum number of idle instances

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
